### PR TITLE
Better the way to capture the amount of chips of the players

### PR DESCRIPTION
**Pull request by imanol309**
Este es el nuevo cambio.

### CODE REVIEW

**Comment by angerimg** [comment]
what do you mean by `better the way`?

**Comment by imanol309** [comment]
Me refiero a (mejor forma).

**Comment by angerimg** [comment]
the way to do the PR is to explain the things you did, explain in the description what you did in the change. and look for how to improve the title because that would not be the way to say that 🤔 it could be like`improving the way to capture chips`, you can see this kind of references on the link I sent to you 😄

**Comment by imanol309** [comment]
I understand, I will take it into account

**Pull request merged**
